openapi: 3.0.1
info:
  title: User API
  description: API for managing users.
  version: 1.0.0
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      description: Retrieves details of a user based on their userId.
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: string
            format: uuid
            example: 3cd63e13-8747-472c-bc1e-3739cad416f4
      responses:
        '200':
          description: Successfully retrieved the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  schemas:
    User:
      type: object
      title: User
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the user
          example: 3cd63e13-8747-472c-bc1e-3739cad416f4
        name:
          type: string
          description: The name of the user
          example: "John Doe"
        email:
          type: string
          description: The email address of the user
          example: "john.doe@example.com"
        createdAt:
          type: string
          format: date-time
          description: The date and time when the user was created
          example: "2023-01-01T12:00:00Z"